---
- name: "copy"
  become: true
  copy:
    src: /home/artifact.tar.gz
    dest: /home/ubuntu/backend-code.tar.gz

- name: start
  shell: |
    cd /home/ubuntu/
    tarxf ackend-code.tar.gz -C /home/circleci/project/backend
    cd /home/circleci/project/backend
    sudo npm install -g npm@latest
    sudo npm install -g webpack-dev-server
    sudo npm install
    sudo npm run build
    sudo pm2 start npm --name backend -- start
